Allow access to optimization direction in optimizer
logicalclocks/maggy pull request #40
Opened 2020-02-25 17:35 UTC by moritzmeister

Add reference in optimizer to the optimization direction. This is required for more advaned optimizers.

Also I am moving the setting of the references out of the init of the experimentdriver. To group things a bit more logically.

@ssheikholeslami can you double check, I am not breaking any ablation functionality. We should unify this across optimization and ablation, as we are passing these as arguments when instantiating the Ablator, whereas in optimization we set them separately.

2020-02-26 09:37 UTC, ssheikholeslami requested changes

2020-02-26 09:37 UTC, ssheikholeslami commented on maggy/core/experimentdriver.py
> +        self.optimizer.direction = self.direction
Why not move this block to under L252?

2020-02-26 09:37 UTC, ssheikholeslami commented on maggy/core/experimentdriver.py
> +        self.optimizer.direction = self.direction
No optimization object will be created if the experiment type is `ablation`, hence this will throw an exception.

2020-02-26 12:08 UTC, ssheikholeslami commented on maggy/core/experimentdriver.py
> +        self.optimizer.direction = self.direction
To unify this across optimization and ablation, I propose something like `AbstractController(ABC)` that contains the common attributes and objects, and `AbstractOptimizer` and `AbstractAblator` would then inherit from it. We can address this in a later PR.

2020-03-05 13:07 UTC, ssheikholeslami commented on maggy/core/experimentdriver.py
> +        self.optimizer.direction = self.direction
We can also implement a `ParameterServer` using an `AbstractController` - I have some ideas about this, let's discuss soon.

2020-04-02 12:54 UTC, moritzmeister commented
Add also reference to trial-store in optimizer, same as for optimization direction

2020-04-02 15:18 UTC, ssheikholeslami approved these changes
LGTM

2020-04-02 15:37 UTC, merged